import util
import  config
obj = util.load_json_utf8(config.tfmatrix_path)
s=str(obj)
i=s.find("x00")
util.print_utf8(s[i-20:i+20])
print(" ")

i=s.find("39474")
util.print_utf8(s[i-20:i+20])
print(" ")
i=s.find("told")
util.print_utf8(s[i-20:i+20])
print(" ")
i=s.find("MRT")
util.print_utf8(s[i-20:i+20])
print(" ")
i=s.find("observe")
util.print_utf8(s[i-20:i+20])
print(" ")